[versions]
mindustry = "v154"

kotlin = "2.2.10"
# TODO My local d8 only supports up to kotlin 2.2 hence we can't use 2.3 yet
kotlinx-coroutines = "1.10.2"

redwood = "0.18.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

redwood-schema = { id = "app.cash.redwood.schema", version.ref = "redwood"}
redwood-widget = { id = "app.cash.redwood.generator.widget", version.ref = "redwood" }
redwood-modifiers = { id = "app.cash.redwood.generator.modifiers", version.ref = "redwood" }
redwood-compose = { id = "app.cash.redwood.generator.compose", version.ref = "redwood" }


[libraries]
arc-core = { group = "com.github.Anuken.Arc", name = "arc-core", version.ref = "mindustry" }
mindustry = {group = "com.github.Anuken.Mindustry", name = "core", version.ref = "mindustry" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# TODO Redwood uses the 1.9.0 runtime internally. We should see if we can force our mod to compile against 1.10.1(or whatever the latest ver is) without breaking redwood.
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version = "1.9.0"}
redwood-schema = {group = "app.cash.redwood", name = "redwood-schema", version.ref = "redwood"}
redwood-compose = {group = "app.cash.redwood", name = "redwood-compose", version.ref = "redwood"}
redwood-widget = {group = "app.cash.redwood", name = "redwood-widget", version.ref = "redwood"}