plugins {
    alias(libs.plugins.kotlin.jvm)
    id("maven-publish")
}

dependencies {
    // The renderer backend depends on the Widgets autogenerated from the schema
    implementation(project(":schema:widget"))
    implementation(project(":schema:modifier"))
    implementation(project(":schema:api"))

    compileOnly(libs.arc.core)
    compileOnly(libs.mindustry)

    implementation(libs.redwood.widget)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            artifactId = project.name
        }
    }
}